### ISSUE TITLE
Data link is disabled.

### ISSUE THREAD

**Issue by BZboys** [viebboy/MultilinearCompressiveLearningFramework#4]
Thank you for your code. But the data link seems to be disabled. Could you check and update it? 

Looking forward to your reply!

**Comment by ece19022** [comment]
> Thank you for your code. But the data link seems to be disabled. Could you check and update it?
> 
> Looking forward to your reply!
@BZboys  can you please let me know if you where able to implement the code?
I've been trying, but stuck with the datasets. please help me out

**Comment by ZhangMeng130** [comment]
@ece19022 Did you find the data?

**Comment by viebboy** [comment]
@12bbb  @ece19022 : I no longer maintain this repo. However, this method is integrated into the `opendr` toolkit in here: https://github.com/opendr-eu/opendr/blob/master/docs/reference/multilinear-compressive-learning.md
