### ISSUE TITLE
exp_configurations.conf_tensor_linearity is not defined but used in train.py

### ISSUE THREAD

**Issue by ZhangMeng130** [viebboy/MultilinearCompressiveLearningFramework#5]

**Comment by viebboy** [comment]
@12bbb: hi, I no longer maintain this repo. However, this method has been integrated into the `opendr` toolkit in here: https://github.com/opendr-eu/opendr/blob/master/docs/reference/multilinear-compressive-learning.md

**Comment by daqiudi** [comment]
@12bbb did you solve it？

**Comment by ZhangMeng130** [comment]
> @12bbb did you solve it？

not yet
